# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ip',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='port',
            field=models.IntegerField(blank=True, default=6800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
