# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170205_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='port',
            field=models.IntegerField(blank=True, default=6800),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.TextField(blank=True, default=''),
        ),
    ]
