# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170205_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
