# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170205_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
