# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170308_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='middlewares',
            field=models.TextField(blank=True, default=''),
        ),
    ]
